id: I7558A678
legacy_id: P008064
ocr_import_info:
  bdrc_scan_id: W1KG25186
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T09:40:44'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T14:09:30.111588+00:00'
last_modified: 2022-08-31 22:09:48.990384
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG25186
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG25186
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: པདྨ་བཀའ་ཐང་།
  author: ཡར་རྗེ་ཨོ་རྒྱན་གླིང་པ།
statistics:
  ocr_word_mean_confidence_index: 0.6610933818599446
  ocr_word_median_confidence_index: 0.8600000143051147
quality: null
bases:
  I1KG25188:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG25188
      total_pages: 402
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG25188.txt
    statistics:
      ocr_word_median_confidence_index: 0.8600000143051147
      ocr_word_mean_confidence_index: 0.6610933818599446
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
