id: I7558A678
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T09:43:30+00:00'
last_modified: '2022-06-08T18:10:27.309469+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25186
  title: པདྨ་བཀའ་ཐང།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    37C3:
      image_group_id: I1KG25188
      title: Volume 1 of pad+ma bka' thang/
      total_pages: 402
      order: 1
      base_file: 37C3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
