id: P008064
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:59:00.249364
source_metadata:
  id: bdr:W1KG25186
  title: པདྨ་བཀའ་ཐང།
  author: ''
  volumes:
    2ca4b80fb05843a3bdb3c87843efee28:
      image_group_id: I1KG25188
      title: Volume 1 of pad+ma bka' thang/
      volume_number: 1
      total_pages: 402
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
