id: P008064
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25186
  title: པདྨ་བཀའ་ཐང།
  author: ''
  volumes:
    6fcd0c7c4d7e42868d0721f2a825820f:
      image_group_id: I1KG25188
      title: ''
      volume_number: 1
      total_pages: 402
ebook_metadata:
  title: པདྨ་བཀའ་ཐང།
  author: ''
  sku: P008064
  cover: cover.jpg
  layers:
  - pagination
